In [1]:
import pandas as pd

In [2]:
data_path = "data/processed_biomarkers_features.csv"
data = pd.read_csv(data_path)
print("processed_data.shape", data.shape)

mrg_data = pd.read_csv("data/merged_formatted.csv")
print("mrg_data.shape: ", mrg_data.shape)

processed_data.shape (11, 13)
mrg_data.shape:  (134, 20784)

In [3]:
#data splitting Pipeline,  labels and features
cols_labels = data.columns.tolist()
cols_labels.pop(-1)


#selecting specific featuers
#seleting features on spot
#cols_labels = ['ABCA9', 'ABCA10', 'SHOX2', 'MAB21L2', 'Outcomes']
#cols_labels = ['ABCA9', 'ABCA10', 'SHOX2', 'MAB21L2', 'IQCK', 'ADIPOQ', 'Outcomes']

#to select specific columns
data_features = pd.read_csv(data_path, usecols = cols_labels)

#to drop sepecific columns
#data_features = pd.read_csv(data_path)
#data_features = data_features.drop(cols_labels, axis=1)

data_labels = pd.read_csv(data_path, usecols = ['Outcomes'])

In [5]:
mrg_data_sel = mrg_data[cols_labels]

In [6]:
print("data_features.shape: ", data_features.shape)
print("mrg_data_sel.shape: ", mrg_data_sel.shape)

data_features.shape:  (11, 12)
mrg_data_sel.shape:  (134, 12)

In [8]:
data_features.head(5)

,EGF,NOTCH3,ESR1,JAG1,NOTCH2,FOXM1,FN1,MYC,CXCL1,TIMP1,CCL2,ANXA5
0,81,940,71,1510,988,192,1975,754,1350,7259,6452,4113
1,607,1729,105,1820,825,141,635,195,180,4954,2812,4663
2,40,1362,126,1558,1931,601,4132,704,1097,22129,11659,7064
3,315,1276,94,924,623,191,287,75,53,990,2303,1080
4,59,123,9,7,39,159,74,10,12,43,243,75

In [7]:
mrg_data_sel.head(5)

,EGF,NOTCH3,ESR1,JAG1,NOTCH2,FOXM1,FN1,MYC,CXCL1,TIMP1,CCL2,ANXA5
0,51,1,9,26,942,1,0,239,13,608,0,1125
1,33,3,11,40,1113,4,0,195,4,695,20,839
2,12,176,241,353,1820,494,3037,1764,40,1558,129,2876
3,161,3,3,13,575,1,0,241,9,975,2,711
4,32,5,12,2,490,0,0,121,1,178,2,503

In [9]:
combined_data = pd.concat([data_features, mrg_data_sel])
print("combined_data.shape: ", combined_data.shape)
combined_data

combined_data.shape:  (145, 12)

,EGF,NOTCH3,ESR1,JAG1,NOTCH2,FOXM1,FN1,MYC,CXCL1,TIMP1,CCL2,ANXA5
0,81,940,71,1510,988,192,1975,754,1350,7259,6452,4113
1,607,1729,105,1820,825,141,635,195,180,4954,2812,4663
2,40,1362,126,1558,1931,601,4132,704,1097,22129,11659,7064
3,315,1276,94,924,623,191,287,75,53,990,2303,1080
4,59,123,9,7,39,159,74,10,12,43,243,75
...,...,...,...,...,...,...,...,...,...,...,...,...
129,111,4,4,30,1182,0,0,80,6,1100,6,1400
130,476,323,0,31,73,0,2,0,37,223,2,1295
131,355,447,0,52,51,2,0,0,80,212,1,485
132,620,654,0,46,87,0,0,0,92,249,20,1499
133,273,254,0,36,53,1,0,0,91,161,5,767

In [10]:
combined_data.to_csv("data/combined_data.csv", index=False)